### ISSUE TITLE
Error message when running

### ISSUE THREAD

**Issue by frdrcv** [t-wissmann/rofi-bibbrowser#1]
Ain't sure if you're still developing/using rofi-bibbrowser, but it seems to be quite an useful script and I would love to use it. When I try to load it, I get the following error:
`Traceback (most recent call last):
  File "./rofi-bibbrowser", line 208, in <module>
    e['_filenames'] = list(generate_filenames(e))
  File "./rofi-bibbrowser", line 128, in generate_filenames
    result = generator(entry)
  File "./rofi-bibbrowser", line 107, in filenameBibID
    return entry['ID']
KeyError: 'ID'`
I also get just before that many warnings about non-standard entries, but I guess rofi-bibbrowser is just not biblatex compatible. I'm using jabref to manage my bibtex library; perhaps is there code produced by jabef that confuse the script?

**Comment by t-wissmann** [comment]
Thanks for using it and for the feedback!

It seems I wrongly assumed that every bibfile entry has an ID (that is the identifier used by the `\cite{...}` macro). While this assumption is reasonable for  bib(la)tex, rofi-bibbrowser does not actually need it.

I have just fixed this by 60b7ac139e1d5edf1e498114ec67d8d566723f68, so please try again

**Comment by frdrcv** [comment]
Thanks for the quick answer, this is working now and... wow! This script is awesome!
(I think I will need to take a look at my bib file if there are missing keys...)

**Comment by t-wissmann** [comment]
Great and Thanks!

Are you happy how the pdf files are renamed?

**Comment by frdrcv** [comment]
Yes, absolutely. Habitually, I just use the last name of the first author with the year of publication to name my pdfs, which can lead to confusion. The information shown by your script in rofi is way more complete.

**Comment by frdrcv** [comment]
Actually, I have a question/recommandation. Could it be possible to use the editor's name instead of the author's when the author's field is empty? For now, I get questions marks for these entries and I can't list all the entries of a researcher if they are the editor. Also, there are some biblatex entries that don't seem to work; I have some @Suppbook, @Suppcollection, @online, etc. in my bibliography and they appear as two questions marks.
![rofibib](https://cloud.githubusercontent.com/assets/7156522/26165614/978072a8-3afe-11e7-9c08-66b21024a008.png)

**Comment by t-wissmann** [comment]
Sorry for not replying to this, I totally forgot this. Now the item formatting falls back to the editor name if there is no author. In the meantime, rofi-bibbrowser uses a better bibtex parser called [biblib](https://github.com/aclements/biblib) -- maybe this also solves the other issues.
Also, I have slightly changes the config file format (see `rofi-bibbrowser --default-config`).
