### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by galou** [t-wissmann/rofi-bibbrowser#3]
I didn't manager to run your plugin with `rofi -show bib:~/.local/share/rofi/rofi-bibbrowser`. The first error I got was:
```
(process:3604): Helper-WARNING **: 14:52:11.644: Failed to set lock on pidfile: Rofi already running?

(process:3604): Helper-WARNING **: 14:52:11.644: Got error: -1 Socket operation on non-socket
Warning: IPA links to multiple entriesWarning: Rauf,Kim,Ryu 2004: Complete Parameter Identification of Parallel Manipulators with Partial Pose Information using a New Measurement Device links to multiple entriesWarning:  links to multiple entriesWarning:  links to multiple entriesWarning:  links to multiple entriesTraceback (most recent call last):
  File "/home/gael/.local/share/rofi/rofi-bibbrowser", line 256, in <module>
    idx,exit_code = call_rofi(menu,  rofi_args)
  File "/home/gael/.local/share/rofi/rofi-bibbrowser", line 37, in call_rofi
    proc.stdin.write((e).encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by t-wissmann** [comment]
rofi-bibbrowser is not supposed to run as a plugin but as a standalone program. This means, one needs to run the executable explicitely, in your case:
```
~/.local/share/rofi/rofi-bibbrowser
```

**Comment by galou** [comment]
OK, I get it. Thanks for the quick reply!
